[2021-06-28 15:20:00,523] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue_distance_eta 2021-06-26T23:45:00+00:00 [queued]>
[2021-06-28 15:20:00,619] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue_distance_eta 2021-06-26T23:45:00+00:00 [queued]>
[2021-06-28 15:20:00,620] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-28 15:20:00,622] {taskinstance.py:1068} INFO - Starting attempt 1 of 4
[2021-06-28 15:20:00,622] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-28 15:20:00,664] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): queue_distance_eta> on 2021-06-26T23:45:00+00:00
[2021-06-28 15:20:00,732] {standard_task_runner.py:52} INFO - Started process 295 to run task
[2021-06-28 15:20:00,941] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'queue_distance_eta', '2021-06-26T23:45:00+00:00', '--job-id', '271', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/analytics_summary.py', '--cfg-path', '/tmp/tmpuo5rmrpj', '--error-file', '/tmp/tmphtj5phb3']
[2021-06-28 15:20:00,942] {standard_task_runner.py:77} INFO - Job 271: Subtask queue_distance_eta
[2021-06-28 15:20:01,760] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.queue_distance_eta 2021-06-26T23:45:00+00:00 [running]> on host 32c9461fc328
[2021-06-28 15:20:02,402] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=queue_distance_eta
AIRFLOW_CTX_EXECUTION_DATE=2021-06-26T23:45:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-26T23:45:00+00:00
[2021-06-28 15:20:02,404] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-28 15:20:12,916] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-28 15:20:15,200] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-28 15:20:15,201] {python.py:151} INFO - Done. Returned value was: None
[2021-06-28 15:20:15,252] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=queue_distance_eta, execution_date=20210626T234500, start_date=20210628T152000, end_date=20210628T152015
[2021-06-28 15:20:15,463] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-28 15:20:15,659] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-06-28 15:39:10,445] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue_distance_eta 2021-06-26T23:45:00+00:00 [queued]>
[2021-06-28 15:39:10,471] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue_distance_eta 2021-06-26T23:45:00+00:00 [queued]>
[2021-06-28 15:39:10,471] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-28 15:39:10,471] {taskinstance.py:1068} INFO - Starting attempt 1 of 4
[2021-06-28 15:39:10,471] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-28 15:39:10,487] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): queue_distance_eta> on 2021-06-26T23:45:00+00:00
[2021-06-28 15:39:10,496] {standard_task_runner.py:52} INFO - Started process 360 to run task
[2021-06-28 15:39:10,503] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'queue_distance_eta', '2021-06-26T23:45:00+00:00', '--job-id', '312', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/analytics_summary.py', '--cfg-path', '/tmp/tmpll489ig_', '--error-file', '/tmp/tmpqpn184l6']
[2021-06-28 15:39:10,504] {standard_task_runner.py:77} INFO - Job 312: Subtask queue_distance_eta
[2021-06-28 15:39:10,609] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.queue_distance_eta 2021-06-26T23:45:00+00:00 [running]> on host 32c9461fc328
[2021-06-28 15:39:10,740] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=queue_distance_eta
AIRFLOW_CTX_EXECUTION_DATE=2021-06-26T23:45:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-26T23:45:00+00:00
[2021-06-28 15:39:10,742] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-28 15:40:11,352] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-28 15:40:12,973] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-28 15:40:12,973] {python.py:151} INFO - Done. Returned value was: None
[2021-06-28 15:40:12,986] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=queue_distance_eta, execution_date=20210626T234500, start_date=20210628T153910, end_date=20210628T154012
[2021-06-28 15:40:13,022] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-28 15:40:13,042] {local_task_job.py:151} INFO - Task exited with return code 0
