[2021-06-15 18:02:10,093] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.customer_servicecentre_logins 2021-06-14T00:00:00+00:00 [queued]>
[2021-06-15 18:02:10,156] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.customer_servicecentre_logins 2021-06-14T00:00:00+00:00 [queued]>
[2021-06-15 18:02:10,158] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 18:02:10,161] {taskinstance.py:1068} INFO - Starting attempt 2 of 3
[2021-06-15 18:02:10,168] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 18:02:10,269] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): customer_servicecentre_logins> on 2021-06-14T00:00:00+00:00
[2021-06-15 18:02:10,279] {standard_task_runner.py:52} INFO - Started process 1534 to run task
[2021-06-15 18:02:10,294] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'customer_servicecentre_logins', '2021-06-14T00:00:00+00:00', '--job-id', '158', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpz3w2mfmd', '--error-file', '/tmp/tmpgr5u3odh']
[2021-06-15 18:02:10,294] {standard_task_runner.py:77} INFO - Job 158: Subtask customer_servicecentre_logins
[2021-06-15 18:02:10,434] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.customer_servicecentre_logins 2021-06-14T00:00:00+00:00 [running]> on host bb8bb196dd92
[2021-06-15 18:02:10,746] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=customer_servicecentre_logins
AIRFLOW_CTX_EXECUTION_DATE=2021-06-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-14T00:00:00+00:00
[2021-06-15 18:02:10,751] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-15 18:02:13,519] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-15 18:02:13,879] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/io/sql.py:1423 UserWarning: The provided table name '21N_customer_servicecentre_logins' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
[2021-06-15 18:02:13,881] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-15 18:02:13,888] {python.py:151} INFO - Done. Returned value was: None
[2021-06-15 18:02:13,934] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=customer_servicecentre_logins, execution_date=20210614T000000, start_date=20210615T180210, end_date=20210615T180213
[2021-06-15 18:02:14,065] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-15 18:02:14,082] {local_task_job.py:151} INFO - Task exited with return code 0
