[2021-06-15 18:01:38,655] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.ambassador_ontime_history 2021-06-14T00:00:00+00:00 [queued]>
[2021-06-15 18:01:38,702] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.ambassador_ontime_history 2021-06-14T00:00:00+00:00 [queued]>
[2021-06-15 18:01:38,703] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 18:01:38,703] {taskinstance.py:1068} INFO - Starting attempt 2 of 3
[2021-06-15 18:01:38,703] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 18:01:38,748] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): ambassador_ontime_history> on 2021-06-14T00:00:00+00:00
[2021-06-15 18:01:38,758] {standard_task_runner.py:52} INFO - Started process 1503 to run task
[2021-06-15 18:01:38,778] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'ambassador_ontime_history', '2021-06-14T00:00:00+00:00', '--job-id', '156', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpk6fczkn_', '--error-file', '/tmp/tmpzmz6kg1m']
[2021-06-15 18:01:38,779] {standard_task_runner.py:77} INFO - Job 156: Subtask ambassador_ontime_history
[2021-06-15 18:01:38,934] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.ambassador_ontime_history 2021-06-14T00:00:00+00:00 [running]> on host bb8bb196dd92
[2021-06-15 18:01:39,259] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=ambassador_ontime_history
AIRFLOW_CTX_EXECUTION_DATE=2021-06-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-14T00:00:00+00:00
[2021-06-15 18:01:39,260] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-15 18:02:07,239] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-15 18:02:09,175] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/io/sql.py:1423 UserWarning: The provided table name '21N_ambassador_ontime_history' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
[2021-06-15 18:02:09,175] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-15 18:02:09,176] {python.py:151} INFO - Done. Returned value was: None
[2021-06-15 18:02:09,222] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=ambassador_ontime_history, execution_date=20210614T000000, start_date=20210615T180138, end_date=20210615T180209
[2021-06-15 18:02:09,325] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-15 18:02:09,435] {local_task_job.py:151} INFO - Task exited with return code 0
