[2021-06-15 17:51:16,770] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.servicecentre_invoices 2021-06-14T00:00:00+00:00 [queued]>
[2021-06-15 17:51:16,854] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.servicecentre_invoices 2021-06-14T00:00:00+00:00 [queued]>
[2021-06-15 17:51:16,855] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 17:51:16,856] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2021-06-15 17:51:16,856] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 17:51:16,928] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): servicecentre_invoices> on 2021-06-14T00:00:00+00:00
[2021-06-15 17:51:16,992] {standard_task_runner.py:52} INFO - Started process 972 to run task
[2021-06-15 17:51:17,029] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'servicecentre_invoices', '2021-06-14T00:00:00+00:00', '--job-id', '149', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmplxlmme42', '--error-file', '/tmp/tmp1u8yqoyp']
[2021-06-15 17:51:17,030] {standard_task_runner.py:77} INFO - Job 149: Subtask servicecentre_invoices
[2021-06-15 17:51:17,277] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.servicecentre_invoices 2021-06-14T00:00:00+00:00 [running]> on host bb8bb196dd92
[2021-06-15 17:51:17,451] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=servicecentre_invoices
AIRFLOW_CTX_EXECUTION_DATE=2021-06-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-14T00:00:00+00:00
[2021-06-15 17:51:17,452] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-15 17:51:26,162] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-15 17:51:26,980] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/io/sql.py:1423 UserWarning: The provided table name '21N_servicecentre_invoices' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
[2021-06-15 17:51:26,980] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-15 17:51:26,981] {python.py:151} INFO - Done. Returned value was: None
[2021-06-15 17:51:27,019] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=servicecentre_invoices, execution_date=20210614T000000, start_date=20210615T175116, end_date=20210615T175127
[2021-06-15 17:51:27,258] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-15 17:51:28,633] {local_task_job.py:151} INFO - Task exited with return code 0
