[2021-06-15 17:51:14,634] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue_repeat 2021-06-14T00:00:00+00:00 [queued]>
[2021-06-15 17:51:14,912] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue_repeat 2021-06-14T00:00:00+00:00 [queued]>
[2021-06-15 17:51:14,912] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 17:51:14,913] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2021-06-15 17:51:14,914] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 17:51:15,076] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): queue_repeat> on 2021-06-14T00:00:00+00:00
[2021-06-15 17:51:15,239] {standard_task_runner.py:52} INFO - Started process 965 to run task
[2021-06-15 17:51:15,294] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'queue_repeat', '2021-06-14T00:00:00+00:00', '--job-id', '145', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpqh78pt8g', '--error-file', '/tmp/tmpl5wmgy3g']
[2021-06-15 17:51:15,296] {standard_task_runner.py:77} INFO - Job 145: Subtask queue_repeat
[2021-06-15 17:51:15,579] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.queue_repeat 2021-06-14T00:00:00+00:00 [running]> on host bb8bb196dd92
[2021-06-15 17:51:15,818] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=queue_repeat
AIRFLOW_CTX_EXECUTION_DATE=2021-06-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-14T00:00:00+00:00
[2021-06-15 17:51:15,819] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-15 17:51:18,776] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-15 17:51:22,698] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/io/sql.py:1423 UserWarning: The provided table name '21N_queue_repeat' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
[2021-06-15 17:51:22,699] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-15 17:51:22,699] {python.py:151} INFO - Done. Returned value was: None
[2021-06-15 17:51:22,929] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=queue_repeat, execution_date=20210614T000000, start_date=20210615T175114, end_date=20210615T175122
[2021-06-15 17:51:23,863] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-15 17:51:23,945] {local_task_job.py:151} INFO - Task exited with return code 0
