[2021-06-15 18:02:26,809] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue_completedby 2021-06-14T00:00:00+00:00 [queued]>
[2021-06-15 18:02:26,898] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue_completedby 2021-06-14T00:00:00+00:00 [queued]>
[2021-06-15 18:02:26,899] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 18:02:26,899] {taskinstance.py:1068} INFO - Starting attempt 2 of 3
[2021-06-15 18:02:26,899] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 18:02:26,981] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): queue_completedby> on 2021-06-14T00:00:00+00:00
[2021-06-15 18:02:27,018] {standard_task_runner.py:52} INFO - Started process 1548 to run task
[2021-06-15 18:02:27,037] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'queue_completedby', '2021-06-14T00:00:00+00:00', '--job-id', '160', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmphsiv_dap', '--error-file', '/tmp/tmpe2k6g3s2']
[2021-06-15 18:02:27,039] {standard_task_runner.py:77} INFO - Job 160: Subtask queue_completedby
[2021-06-15 18:02:27,415] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.queue_completedby 2021-06-14T00:00:00+00:00 [running]> on host bb8bb196dd92
[2021-06-15 18:02:27,671] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=queue_completedby
AIRFLOW_CTX_EXECUTION_DATE=2021-06-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-14T00:00:00+00:00
[2021-06-15 18:02:27,673] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-15 18:02:30,471] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-15 18:02:35,887] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/io/sql.py:1423 UserWarning: The provided table name '21N_queue_completedby' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
[2021-06-15 18:02:35,888] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-15 18:02:35,888] {python.py:151} INFO - Done. Returned value was: None
[2021-06-15 18:02:36,020] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=queue_completedby, execution_date=20210614T000000, start_date=20210615T180226, end_date=20210615T180236
[2021-06-15 18:02:36,307] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-15 18:02:36,361] {local_task_job.py:151} INFO - Task exited with return code 0
