[2021-06-14 12:48:59,598] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.dealer_master 2021-06-13T00:00:00+00:00 [queued]>
[2021-06-14 12:49:00,015] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.dealer_master 2021-06-13T00:00:00+00:00 [queued]>
[2021-06-14 12:49:00,016] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-14 12:49:00,016] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2021-06-14 12:49:00,016] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-14 12:49:00,120] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): dealer_master> on 2021-06-13T00:00:00+00:00
[2021-06-14 12:49:00,284] {standard_task_runner.py:52} INFO - Started process 374 to run task
[2021-06-14 12:49:00,366] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'dealer_master', '2021-06-13T00:00:00+00:00', '--job-id', '37', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpzaov23v6', '--error-file', '/tmp/tmp8kofsklw']
[2021-06-14 12:49:00,414] {standard_task_runner.py:77} INFO - Job 37: Subtask dealer_master
[2021-06-14 12:49:00,997] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.dealer_master 2021-06-13T00:00:00+00:00 [running]> on host 7874826b9cd7
[2021-06-14 12:49:01,608] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=dealer_master
AIRFLOW_CTX_EXECUTION_DATE=2021-06-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-13T00:00:00+00:00
[2021-06-14 12:49:01,609] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-14 12:49:04,552] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-14 12:49:04,763] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/first_dag.py", line 238, in dealer_master
    index=False)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 2615, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 598, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 1393, in to_sql
    table.create()
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 725, in create
    self.pd_sql.drop_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 1453, in drop_table
    self.meta.reflect(only=[table_name], schema=schema)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4612, in reflect
    "in %r%s: (%s)" % (bind.engine, s, ", ".join(missing))
sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(mysql://root:***@host.docker.internal:3306/21north) schema '21north': (21N_dealer_master)
[2021-06-14 12:49:04,769] {taskinstance.py:1531} INFO - Marking task as UP_FOR_RETRY. dag_id=summary_db, task_id=dealer_master, execution_date=20210613T000000, start_date=20210614T124859, end_date=20210614T124904
[2021-06-14 12:49:04,887] {local_task_job.py:151} INFO - Task exited with return code 1
[2021-06-14 15:28:06,845] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.dealer_master 2021-06-13T00:00:00+00:00 [queued]>
[2021-06-14 15:28:06,931] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.dealer_master 2021-06-13T00:00:00+00:00 [queued]>
[2021-06-14 15:28:06,932] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-14 15:28:06,932] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2021-06-14 15:28:06,932] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-14 15:28:07,052] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): dealer_master> on 2021-06-13T00:00:00+00:00
[2021-06-14 15:28:07,267] {standard_task_runner.py:52} INFO - Started process 796 to run task
[2021-06-14 15:28:07,321] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'dealer_master', '2021-06-13T00:00:00+00:00', '--job-id', '78', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp5bclimg1', '--error-file', '/tmp/tmpne_ec9o8']
[2021-06-14 15:28:07,322] {standard_task_runner.py:77} INFO - Job 78: Subtask dealer_master
[2021-06-14 15:28:08,193] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.dealer_master 2021-06-13T00:00:00+00:00 [running]> on host 7874826b9cd7
[2021-06-14 15:28:09,116] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=dealer_master
AIRFLOW_CTX_EXECUTION_DATE=2021-06-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-13T00:00:00+00:00
[2021-06-14 15:28:09,117] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-14 15:28:13,601] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-14 15:28:27,154] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-14 15:28:27,156] {python.py:151} INFO - Done. Returned value was: None
[2021-06-14 15:28:27,188] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=dealer_master, execution_date=20210613T000000, start_date=20210614T152806, end_date=20210614T152827
[2021-06-14 15:28:27,342] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-14 15:28:27,539] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-06-14 18:33:53,041] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.dealer_master 2021-06-13T00:00:00+00:00 [queued]>
[2021-06-14 18:33:53,656] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.dealer_master 2021-06-13T00:00:00+00:00 [queued]>
[2021-06-14 18:33:53,658] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-14 18:33:53,663] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2021-06-14 18:33:53,664] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-14 18:33:53,844] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): dealer_master> on 2021-06-13T00:00:00+00:00
[2021-06-14 18:33:53,989] {standard_task_runner.py:52} INFO - Started process 249 to run task
[2021-06-14 18:33:54,217] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'dealer_master', '2021-06-13T00:00:00+00:00', '--job-id', '103', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpu4xdqscm', '--error-file', '/tmp/tmpd4se9r0z']
[2021-06-14 18:33:54,218] {standard_task_runner.py:77} INFO - Job 103: Subtask dealer_master
[2021-06-14 18:33:55,774] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.dealer_master 2021-06-13T00:00:00+00:00 [running]> on host 89c270a4555f
[2021-06-14 18:33:56,820] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=dealer_master
AIRFLOW_CTX_EXECUTION_DATE=2021-06-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-13T00:00:00+00:00
[2021-06-14 18:33:56,823] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-14 18:34:14,218] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-14 18:34:27,724] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-14 18:34:27,734] {python.py:151} INFO - Done. Returned value was: None
[2021-06-14 18:34:27,842] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=dealer_master, execution_date=20210613T000000, start_date=20210614T183353, end_date=20210614T183427
[2021-06-14 18:34:28,204] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-14 18:34:28,573] {local_task_job.py:151} INFO - Task exited with return code 0
