[2021-06-14 12:49:18,849] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue 2021-06-13T00:00:00+00:00 [queued]>
[2021-06-14 12:49:19,160] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue 2021-06-13T00:00:00+00:00 [queued]>
[2021-06-14 12:49:19,160] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-14 12:49:19,160] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2021-06-14 12:49:19,161] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-14 12:49:19,337] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): queue> on 2021-06-13T00:00:00+00:00
[2021-06-14 12:49:19,360] {standard_task_runner.py:52} INFO - Started process 413 to run task
[2021-06-14 12:49:19,416] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'queue', '2021-06-13T00:00:00+00:00', '--job-id', '55', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp5sh3nne6', '--error-file', '/tmp/tmp1pb3q5c3']
[2021-06-14 12:49:19,420] {standard_task_runner.py:77} INFO - Job 55: Subtask queue
[2021-06-14 12:49:19,659] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.queue 2021-06-13T00:00:00+00:00 [running]> on host 7874826b9cd7
[2021-06-14 12:49:19,863] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=queue
AIRFLOW_CTX_EXECUTION_DATE=2021-06-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-13T00:00:00+00:00
[2021-06-14 12:49:19,864] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-14 12:50:34,169] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-14 12:50:35,306] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/io/sql.py:1423 UserWarning: The provided table name '21N_queue' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
[2021-06-14 12:50:35,306] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-14 12:50:35,307] {python.py:151} INFO - Done. Returned value was: None
[2021-06-14 12:50:35,320] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=queue, execution_date=20210613T000000, start_date=20210614T124918, end_date=20210614T125035
[2021-06-14 12:50:35,374] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-14 12:50:35,427] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-06-14 15:28:32,169] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue 2021-06-13T00:00:00+00:00 [queued]>
[2021-06-14 15:28:32,544] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue 2021-06-13T00:00:00+00:00 [queued]>
[2021-06-14 15:28:32,544] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-14 15:28:32,545] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2021-06-14 15:28:32,545] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-14 15:28:32,688] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): queue> on 2021-06-13T00:00:00+00:00
[2021-06-14 15:28:32,899] {standard_task_runner.py:52} INFO - Started process 840 to run task
[2021-06-14 15:28:32,974] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'queue', '2021-06-13T00:00:00+00:00', '--job-id', '91', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp_u029255', '--error-file', '/tmp/tmpiu51rdow']
[2021-06-14 15:28:33,013] {standard_task_runner.py:77} INFO - Job 91: Subtask queue
[2021-06-14 15:28:34,731] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.queue 2021-06-13T00:00:00+00:00 [running]> on host 7874826b9cd7
[2021-06-14 15:28:36,170] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=queue
AIRFLOW_CTX_EXECUTION_DATE=2021-06-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-13T00:00:00+00:00
[2021-06-14 15:28:36,174] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-14 15:30:27,975] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-14 15:30:30,157] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/io/sql.py:1423 UserWarning: The provided table name '21N_queue' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
[2021-06-14 15:30:30,158] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-14 15:30:30,162] {python.py:151} INFO - Done. Returned value was: None
[2021-06-14 15:30:30,222] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=queue, execution_date=20210613T000000, start_date=20210614T152832, end_date=20210614T153030
[2021-06-14 15:30:30,385] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-14 15:30:30,420] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-06-14 18:34:37,228] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue 2021-06-13T00:00:00+00:00 [queued]>
[2021-06-14 18:34:37,489] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.queue 2021-06-13T00:00:00+00:00 [queued]>
[2021-06-14 18:34:37,491] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-14 18:34:37,492] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2021-06-14 18:34:37,492] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-14 18:34:37,531] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): queue> on 2021-06-13T00:00:00+00:00
[2021-06-14 18:34:37,573] {standard_task_runner.py:52} INFO - Started process 307 to run task
[2021-06-14 18:34:37,650] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'queue', '2021-06-13T00:00:00+00:00', '--job-id', '124', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp8w2ldxdw', '--error-file', '/tmp/tmpsjbyetaw']
[2021-06-14 18:34:37,660] {standard_task_runner.py:77} INFO - Job 124: Subtask queue
[2021-06-14 18:34:38,324] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.queue 2021-06-13T00:00:00+00:00 [running]> on host 89c270a4555f
[2021-06-14 18:34:39,009] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=queue
AIRFLOW_CTX_EXECUTION_DATE=2021-06-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-13T00:00:00+00:00
[2021-06-14 18:34:39,012] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-14 18:35:40,190] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-14 18:35:41,921] {logging_mixin.py:104} WARNING - /home/***/.local/lib/python3.6/site-packages/pandas/io/sql.py:1423 UserWarning: The provided table name '21N_queue' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
[2021-06-14 18:35:41,922] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-14 18:35:41,922] {python.py:151} INFO - Done. Returned value was: None
[2021-06-14 18:35:41,955] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=queue, execution_date=20210613T000000, start_date=20210614T183437, end_date=20210614T183541
[2021-06-14 18:35:42,054] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-14 18:35:42,073] {local_task_job.py:151} INFO - Task exited with return code 0
